import {LOCATIONS,RESOURCES} from "./AntColonyData.js";
import {population,mods,clamp,fmt} from "./AntColonyEngine.js";

function rr(ctx,x,y,w,h,r){ctx.beginPath();ctx.roundRect(x,y,w,h,r);}
function nestPos(W,H){return {x:W*.50,y:H*.54};}
export function locationPos(loc,W,H){const n=nestPos(W,H),rad=Math.min(W,H)*loc.dist;return {x:n.x+Math.cos(loc.angle)*rad,y:n.y+Math.sin(loc.angle)*rad*.72};}
export function render(ctx,s,W,H,hover=null){ctx.clearRect(0,0,W,H);drawGround(ctx,s,W,H);drawTrails(ctx,s,W,H);drawLocations(ctx,s,W,H,hover);drawNest(ctx,s,W,H);drawAgents(ctx,s,W,H);drawRaid(ctx,s,W,H);drawEvent(ctx,s,W,H);drawFx(ctx,s,W,H);drawHud(ctx,s,W,H);}
function drawGround(ctx,s,W,H){
  const g=ctx.createLinearGradient(0,0,0,H);g.addColorStop(0,"#607e48");g.addColorStop(1,"#2e5135");ctx.fillStyle=g;ctx.fillRect(0,0,W,H);
  ctx.fillStyle="rgba(255,240,174,.08)";for(let i=0;i<60;i++){const x=(i*97.3)%W,y=(i*57.7)%H,r=2+(i%5);ctx.beginPath();ctx.arc(x,y,r,0,Math.PI*2);ctx.fill();}
  ctx.strokeStyle="rgba(32,78,42,.34)";ctx.lineWidth=1;for(let i=0;i<95;i++){const x=(i*83.1)%W,y=(i*41.7)%H,len=5+(i%8);ctx.beginPath();ctx.moveTo(x,y);ctx.lineTo(x+Math.sin(i)*4,y-len);ctx.stroke();}
}
function drawTrails(ctx,s,W,H){const n=nestPos(W,H);for(const l of LOCATIONS){if(population(s)<l.unlockPop)continue;const p=locationPos(l,W,H),boost=(s.boosts[l.id]||0)>0;ctx.strokeStyle=boost?"rgba(138,255,179,.45)":"rgba(50,38,23,.28)";ctx.lineWidth=boost?7:5;ctx.setLineDash([9,8]);ctx.beginPath();ctx.moveTo(n.x,n.y);ctx.quadraticCurveTo((n.x+p.x)/2+Math.sin(l.angle)*25,(n.y+p.y)/2-Math.cos(l.angle)*18,p.x,p.y);ctx.stroke();ctx.setLineDash([]);}}
function drawLocations(ctx,s,W,H,hover){
  for(const l of LOCATIONS){const p=locationPos(l,W,H),locked=population(s)<l.unlockPop,hot=hover===l.id,boost=(s.boosts[l.id]||0)>0;ctx.save();ctx.translate(p.x,p.y);ctx.globalAlpha=locked?.24:1;ctx.shadowColor=boost?"#86f3ad":"#000";ctx.shadowBlur=boost?18:6;ctx.fillStyle=hot?"#243e2c":"#1e3425";ctx.beginPath();ctx.arc(0,0,32,0,Math.PI*2);ctx.fill();ctx.strokeStyle=locked?"#586257":boost?"#89f0ae":"#79936a";ctx.lineWidth=3;ctx.stroke();ctx.font="24px sans-serif";ctx.textAlign="center";ctx.textBaseline="middle";ctx.fillText(locked?"🔒":l.icon,0,-1);ctx.restore();ctx.textAlign="center";ctx.font="900 10px sans-serif";ctx.fillStyle=locked?"#b9c0b6":"#eef4df";ctx.fillText(locked?`Unlock ${l.unlockPop} ants`:l.name,p.x,p.y+48);if(!locked&&boost){ctx.fillStyle="#9bffc0";ctx.font="800 9px sans-serif";ctx.fillText(`SURGE ${Math.ceil(s.boosts[l.id])}s`,p.x,p.y+61);}}
}
function drawNest(ctx,s,W,H){
  const n=nestPos(W,H),p=population(s),scale=1+Math.min(.45,Math.log10(Math.max(10,p))/7);ctx.save();ctx.translate(n.x,n.y);ctx.scale(scale,scale);
  const g=ctx.createRadialGradient(0,-8,5,0,0,66);g.addColorStop(0,"#b58a55");g.addColorStop(1,"#735136");ctx.fillStyle=g;ctx.beginPath();ctx.ellipse(0,8,68,45,0,0,Math.PI*2);ctx.fill();ctx.fillStyle="#332419";ctx.beginPath();ctx.ellipse(0,3,24,15,0,0,Math.PI*2);ctx.fill();ctx.strokeStyle="rgba(230,195,137,.35)";ctx.lineWidth=2;for(let r=32;r<62;r+=11){ctx.beginPath();ctx.ellipse(0,9,r,r*.55,0,Math.PI,Math.PI*2);ctx.stroke();}ctx.restore();
  ctx.textAlign="center";ctx.fillStyle="#fff4d0";ctx.font="1000 13px sans-serif";ctx.fillText(`ANTHILL · ${p} ANTS`,n.x,n.y+70);ctx.fillStyle="#c8d2bd";ctx.font="800 10px sans-serif";ctx.fillText(`${s.workers} workers · ${s.soldiers} soldiers · ${s.nurses} nurses`,n.x,n.y+86);
}
function pathPoint(l,t,W,H,offset=0){const n=nestPos(W,H),p=locationPos(l,W,H),cx=(n.x+p.x)/2+Math.sin(l.angle)*25,cy=(n.y+p.y)/2-Math.cos(l.angle)*18,u=1-t;const x=(u*u*n.x+2*u*t*cx+t*t*p.x),y=(u*u*n.y+2*u*t*cy+t*t*p.y),dx=2*u*(cx-n.x)+2*t*(p.x-cx),dy=2*u*(cy-n.y)+2*t*(p.y-cy),len=Math.max(1,Math.hypot(dx,dy));return {x:x-dy/len*offset*3,y:y+dx/len*offset*3,ang:Math.atan2(dy,dx)};}
function drawAgents(ctx,s,W,H){
  for(let i=0;i<s.agents.length;i++){const a=s.agents[i],l=LOCATIONS.find(x=>x.id===a.loc)||LOCATIONS[0],pt=pathPoint(l,a.t,W,H,a.offset);ctx.save();ctx.translate(pt.x,pt.y);ctx.rotate(pt.ang+(a.dir<0?Math.PI:0));const sz=2.3+(i%4)*.18;ctx.fillStyle="#181311";ctx.beginPath();ctx.ellipse(-sz*1.7,0,sz*1.1,sz*.8,0,0,Math.PI*2);ctx.ellipse(0,0,sz,sz*.75,0,0,Math.PI*2);ctx.ellipse(sz*1.65,0,sz*.8,sz*.7,0,0,Math.PI*2);ctx.fill();ctx.strokeStyle="#201715";ctx.lineWidth=.8;for(const sy of [-1,1]){for(const xx of [-1.2,0,1.15]){ctx.beginPath();ctx.moveTo(xx*sz,sy*.3);ctx.lineTo((xx-.2)*sz,sy*2.1);ctx.stroke();}}if(a.carry){ctx.fillStyle=RESOURCES[l.resource].color;ctx.beginPath();ctx.arc(-sz*2.1,-sz*1.6,sz*.9,0,Math.PI*2);ctx.fill();}ctx.restore();}
}
function drawRaid(ctx,s,W,H){if(!s.raid)return;const x=W*.52,y=H*.23,pct=clamp(s.raid.hp/s.raid.maxHp,0,1);ctx.fillStyle="rgba(34,17,13,.82)";rr(ctx,x-150,y-30,300,55,10);ctx.fill();ctx.fillStyle="#ffd8c9";ctx.textAlign="center";ctx.font="1000 12px sans-serif";ctx.fillText(`${s.raid.name.toUpperCase()} · ${Math.ceil(s.raid.time)}s`,x,y-9);ctx.fillStyle="#47231f";ctx.fillRect(x-125,y+2,250,10);ctx.fillStyle="#e56654";ctx.fillRect(x-125,y+2,250*pct,10);}
function drawEvent(ctx,s,W,H){if(!s.event)return;ctx.fillStyle="rgba(20,38,26,.86)";rr(ctx,12,12,185,43,9);ctx.fill();ctx.fillStyle=s.event.color;ctx.font="900 11px sans-serif";ctx.textAlign="left";ctx.fillText(s.event.name.toUpperCase(),24,31);ctx.fillStyle="#cce0ce";ctx.font="700 9px sans-serif";ctx.fillText(`${s.event.mult.toFixed(1)}× ${s.event.resource} · ${Math.ceil(s.event.time)}s`,24,45);}
function drawFx(ctx,s,W,H){for(const f of s.floats){const a=clamp(f.life/f.max,0,1);ctx.save();ctx.globalAlpha=Math.min(1,a*1.6);ctx.font=`1000 ${Math.round(15*f.scale)}px sans-serif`;ctx.textAlign="center";ctx.lineWidth=4;ctx.strokeStyle="#000a";ctx.strokeText(f.text,f.x*W,f.y*H);ctx.fillStyle=f.color;ctx.shadowColor=f.color;ctx.shadowBlur=7;ctx.fillText(f.text,f.x*W,f.y*H);ctx.restore();}for(const p of s.particles){const a=clamp(p.life/p.max,0,1);ctx.globalAlpha=a;ctx.fillStyle=p.color;ctx.beginPath();ctx.arc(p.x*W,p.y*H,4*p.size,0,Math.PI*2);ctx.fill();ctx.globalAlpha=1;}}
function drawHud(ctx,s,W,H){const m=mods(s),p=population(s);ctx.fillStyle="rgba(11,24,16,.75)";rr(ctx,W-205,12,193,62,9);ctx.fill();ctx.fillStyle="#eaf2df";ctx.textAlign="right";ctx.font="900 11px sans-serif";ctx.fillText(`COLONY ${p} / ${Math.floor(m.popCap)}`,W-24,32);ctx.fillStyle="#9eb29d";ctx.font="700 9px sans-serif";ctx.fillText(`${s.agents.length} visual foragers · ${fmt(s.totalTrips)} trips`,W-24,48);ctx.fillText(`birth ~${Math.max(.55,5.5/(m.birth*(1+Math.sqrt(Math.max(1,p))/20))).toFixed(1)}s`,W-24,63);}
