import { CONFIG, TEAM_DEFS } from './CellArenaData.js';
import { clamp, radius, shade, ownerById, center, aliveOwners } from './CellArenaEngine.js';

function screen(camera,width,height,x,y){return{x:width/2+(x-camera.x)*camera.zoom,y:height/2+(y-camera.y)*camera.zoom};}
function visible(p,r,w,h){return !(p.x<-r||p.y<-r||p.x>w+r||p.y>h+r);}

function drawGrid(ctx,world,camera,w,h,dark){
  ctx.fillStyle=dark?'#15191f':'#f4f4f4';ctx.fillRect(0,0,w,h);
  const l=camera.x-w/2/camera.zoom,r=camera.x+w/2/camera.zoom,t=camera.y-h/2/camera.zoom,b=camera.y+h/2/camera.zoom,g=CONFIG.gridSize,sx=Math.floor(l/g)*g,sy=Math.floor(t/g)*g;
  ctx.strokeStyle=dark?'#ffffff0d':'#00000012';ctx.lineWidth=1;ctx.beginPath();for(let x=sx;x<=r;x+=g){const p=screen(camera,w,h,x,0).x;ctx.moveTo(p,0);ctx.lineTo(p,h)}for(let y=sy;y<=b;y+=g){const p=screen(camera,w,h,0,y).y;ctx.moveTo(0,p);ctx.lineTo(w,p)}ctx.stroke();
  const a=screen(camera,w,h,0,0),z=screen(camera,w,h,world.size,world.size);ctx.strokeStyle=dark?'#ffffff55':'#0006';ctx.lineWidth=4;ctx.strokeRect(a.x,a.y,z.x-a.x,z.y-a.y);
}
function drawSafeZone(ctx,world,camera,w,h){
  if(!world.safeZone)return;const z=world.safeZone,p=screen(camera,w,h,z.x,z.y),r=z.r*camera.zoom;
  ctx.save();ctx.fillStyle='rgba(224,69,74,.12)';ctx.beginPath();ctx.rect(0,0,w,h);ctx.arc(p.x,p.y,r,0,Math.PI*2,true);ctx.fill('evenodd');ctx.strokeStyle='#f36b6ecc';ctx.lineWidth=4;ctx.setLineDash([12,9]);ctx.beginPath();ctx.arc(p.x,p.y,r,0,Math.PI*2);ctx.stroke();ctx.restore();
}
function drawHotZones(ctx,world,camera,w,h){
  for(const z of world.hotZones){const p=screen(camera,w,h,z.x,z.y),r=z.r*camera.zoom;if(!visible(p,r,w,h))continue;ctx.save();const pulse=1+Math.sin(z.phase*2)*.03;ctx.fillStyle='rgba(244,180,77,.10)';ctx.strokeStyle='rgba(255,196,93,.78)';ctx.lineWidth=3;ctx.setLineDash([10,8]);ctx.beginPath();ctx.arc(p.x,p.y,r*pulse,0,Math.PI*2);ctx.fill();ctx.stroke();ctx.setLineDash([]);ctx.fillStyle='#ffd273';ctx.font='900 11px Arial';ctx.textAlign='center';ctx.fillText('NUTRIENT CONTROL',p.x,p.y-r-8);ctx.restore();}
}
function drawFood(ctx,world,camera,w,h){for(const f of world.food){const p=screen(camera,w,h,f.x,f.y),r=f.r*camera.zoom;if(!visible(p,r,w,h))continue;ctx.save();if(f.golden){ctx.shadowColor='#ffd75c';ctx.shadowBlur=Math.max(3,8*camera.zoom)}ctx.fillStyle=f.color;ctx.beginPath();ctx.arc(p.x,p.y,Math.max(1.4,r),0,Math.PI*2);ctx.fill();ctx.restore();}}
function drawVirus(ctx,world,camera,w,h,v){const p=screen(camera,w,h,v.x,v.y),r=v.r*camera.zoom;if(!visible(p,r,w,h))return;ctx.save();ctx.translate(p.x,p.y);ctx.fillStyle=v.red?'#d9474d':'#35b754';ctx.strokeStyle=v.red?'#8f262c':'#208b39';ctx.lineWidth=Math.max(1.4,camera.zoom*2);ctx.beginPath();for(let i=0;i<56;i++){const a=i/56*Math.PI*2,rr=r*(i%2===0?1.13:.91),x=Math.cos(a)*rr,y=Math.sin(a)*rr;i?ctx.lineTo(x,y):ctx.moveTo(x,y)}ctx.closePath();ctx.fill();ctx.stroke();ctx.fillStyle='#ffffff22';ctx.beginPath();ctx.arc(-r*.2,-r*.2,r*.45,0,Math.PI*2);ctx.fill();if(v.fed>0){ctx.fillStyle='#fff';ctx.font=`800 ${Math.max(7,r*.18)}px Arial`;ctx.textAlign='center';ctx.fillText(`${Math.floor(v.fed)}/${CONFIG.virusFeedPieces}`,0,2)}ctx.restore();}
function drawSpawner(ctx,camera,w,h,s){const p=screen(camera,w,h,s.x,s.y),pulse=1+Math.sin(s.phase)*.055,r=s.r*1.12*camera.zoom*pulse;if(!visible(p,r,w,h))return;ctx.save();ctx.translate(p.x,p.y);ctx.fillStyle='#d9434e';ctx.strokeStyle='#8d202d';ctx.lineWidth=Math.max(2,camera.zoom*2.5);ctx.shadowBlur=Math.max(5,15*camera.zoom);ctx.shadowColor='#ff4b5f88';ctx.beginPath();for(let i=0;i<64;i++){const a=i/64*Math.PI*2,rr=r*(i%2===0?1.12:.90),x=Math.cos(a)*rr,y=Math.sin(a)*rr;i?ctx.lineTo(x,y):ctx.moveTo(x,y)}ctx.closePath();ctx.fill();ctx.stroke();ctx.shadowBlur=0;ctx.strokeStyle='#ffb0b6aa';ctx.beginPath();ctx.arc(0,0,r*.53,0,Math.PI*2);ctx.stroke();ctx.fillStyle='#fff';ctx.font=`900 ${Math.max(8,r*.20)}px Arial`;ctx.textAlign='center';ctx.textBaseline='middle';ctx.fillText('●',0,0);ctx.restore();}
function drawMother(ctx,camera,w,h,m){const p=screen(camera,w,h,m.x,m.y),r=m.r*camera.zoom;if(!visible(p,r,w,h))return;ctx.save();ctx.translate(p.x,p.y);ctx.rotate(m.phase*.08);ctx.shadowColor='#82ef96';ctx.shadowBlur=18;ctx.fillStyle='#49b95e';ctx.strokeStyle='#2b873d';ctx.lineWidth=Math.max(2,camera.zoom*3);ctx.beginPath();for(let i=0;i<44;i++){const a=i/44*6.28,rr=r*(i%2?0.94:1.08);i?ctx.lineTo(Math.cos(a)*rr,Math.sin(a)*rr):ctx.moveTo(Math.cos(a)*rr,Math.sin(a)*rr)}ctx.closePath();ctx.fill();ctx.stroke();ctx.fillStyle='#dbffd855';ctx.beginPath();ctx.arc(0,0,r*.48,0,6.28);ctx.fill();ctx.fillStyle='#f0ffe9';ctx.font=`900 ${Math.max(9,r*.16)}px Arial`;ctx.textAlign='center';ctx.fillText('MOTHER',0,3);ctx.restore();}
function drawPortal(ctx,camera,w,h,p){const sp=screen(camera,w,h,p.x,p.y),r=p.r*camera.zoom;if(!visible(sp,r,w,h))return;ctx.save();ctx.translate(sp.x,sp.y);ctx.rotate(p.phase*.4);ctx.shadowColor='#8e72ef';ctx.shadowBlur=14;for(let i=0;i<3;i++){ctx.strokeStyle=i===1?'#58d5e8':'#a57af2';ctx.lineWidth=Math.max(2,4*camera.zoom);ctx.beginPath();ctx.arc(0,0,r*(.52+i*.20),i*.6,6.28-i*.4);ctx.stroke()}ctx.restore();}
function drawBumper(ctx,camera,w,h,b){const p=screen(camera,w,h,b.x,b.y),r=b.r*camera.zoom;if(!visible(p,r,w,h))return;ctx.save();ctx.translate(p.x,p.y);ctx.shadowColor='#f4a44d';ctx.shadowBlur=10;ctx.fillStyle='#e69143';ctx.strokeStyle='#9f5724';ctx.lineWidth=Math.max(2,3*camera.zoom);ctx.beginPath();ctx.arc(0,0,r,0,6.28);ctx.fill();ctx.stroke();ctx.strokeStyle='#ffd39a';ctx.lineWidth=Math.max(1,2*camera.zoom);ctx.beginPath();ctx.arc(0,0,r*.52,0,6.28);ctx.stroke();ctx.fillStyle='#fff2dc';ctx.font=`900 ${Math.max(8,r*.20)}px Arial`;ctx.textAlign='center';ctx.fillText('↯',0,4);ctx.restore();}
function drawCloud(ctx,camera,w,h,c){const p=screen(camera,w,h,c.x,c.y),r=c.r*camera.zoom;if(!visible(p,r,w,h))return;ctx.save();const g=ctx.createRadialGradient(p.x,p.y,0,p.x,p.y,r);g.addColorStop(0,'rgba(255,219,92,.18)');g.addColorStop(1,'rgba(255,219,92,0)');ctx.fillStyle=g;ctx.beginPath();ctx.arc(p.x,p.y,r,0,6.28);ctx.fill();ctx.strokeStyle='rgba(255,220,101,.32)';ctx.setLineDash([7,8]);ctx.beginPath();ctx.arc(p.x,p.y,r*.78,0,6.28);ctx.stroke();ctx.restore();}
function drawComet(ctx,camera,w,h,c){const p=screen(camera,w,h,c.x,c.y),r=11*camera.zoom;if(!visible(p,80,w,h))return;ctx.save();ctx.strokeStyle='#ffd75a99';ctx.lineWidth=Math.max(2,5*camera.zoom);ctx.beginPath();ctx.moveTo(p.x-c.vx*.09*camera.zoom,p.y-c.vy*.09*camera.zoom);ctx.lineTo(p.x,p.y);ctx.stroke();ctx.shadowColor='#ffe98a';ctx.shadowBlur=14;ctx.fillStyle='#fff1a0';ctx.beginPath();ctx.arc(p.x,p.y,Math.max(3,r),0,6.28);ctx.fill();ctx.restore();}
function drawBossFragments(ctx,world,camera,w,h){for(const f of world.bossFragments){const p=screen(camera,w,h,f.x,f.y),r=f.r*camera.zoom;if(!visible(p,r,w,h))continue;ctx.save();ctx.shadowColor=f.color;ctx.shadowBlur=8;ctx.fillStyle=f.color;ctx.beginPath();ctx.arc(p.x,p.y,Math.max(2,r),0,6.28);ctx.fill();ctx.strokeStyle='#ffffff99';ctx.lineWidth=1;ctx.stroke();ctx.restore();}}
function drawEjected(ctx,world,camera,w,h){for(const e of world.ejected){const p=screen(camera,w,h,e.x,e.y),r=e.r*camera.zoom;if(!visible(p,r,w,h))continue;ctx.fillStyle='#ef9da8';ctx.strokeStyle='#b64a5a55';ctx.lineWidth=1;ctx.beginPath();ctx.arc(p.x,p.y,Math.max(2,r),0,6.28);ctx.fill();ctx.stroke();}}
function drawCell(ctx,world,camera,w,h,c){
  if(!c.alive)return;const o=ownerById(world,c.ownerId);if(!o)return;const p=screen(camera,w,h,c.x,c.y),r=c.r*camera.zoom;if(!visible(p,r+20,w,h))return;ctx.save();ctx.translate(p.x,p.y);
  ctx.fillStyle=o.color;ctx.strokeStyle=o.isBoss?'#fff0c8':shade(o.color,-22);ctx.lineWidth=clamp(r*.055,1.4,8);ctx.shadowColor=o.isBoss?o.color:'transparent';ctx.shadowBlur=o.isBoss?20:0;ctx.beginPath();ctx.arc(0,0,Math.max(2,r),0,6.28);ctx.fill();ctx.stroke();
  const sh=ctx.createRadialGradient(-r*.28,-r*.32,r*.05,0,0,r);sh.addColorStop(0,'#ffffff38');sh.addColorStop(.6,'#ffffff08');sh.addColorStop(1,'#0000000b');ctx.fillStyle=sh;ctx.beginPath();ctx.arc(0,0,Math.max(1,r-ctx.lineWidth),0,6.28);ctx.fill();
  if(o.spawnShield>0){ctx.strokeStyle='#ffffffcc';ctx.lineWidth=Math.max(1.5,3*camera.zoom);ctx.setLineDash([6,5]);ctx.beginPath();ctx.arc(0,0,r+5,0,6.28);ctx.stroke();ctx.setLineDash([]);}
  if(world.mode.teams&&o.team!=null){ctx.strokeStyle=TEAM_DEFS[o.team].dark;ctx.lineWidth=Math.max(2,ctx.lineWidth*.72);ctx.beginPath();ctx.arc(0,0,Math.max(2,r-ctx.lineWidth*.9),0,6.28);ctx.stroke();}
  if(r>13){const fs=clamp(r*.33,9,34);ctx.fillStyle='white';ctx.strokeStyle='#0008';ctx.lineWidth=clamp(fs*.10,1.4,4);ctx.font=`700 ${fs}px Arial`;ctx.textAlign='center';ctx.textBaseline='middle';const yy=r>34?-fs*.16:0;ctx.strokeText(o.name,0,yy);ctx.fillText(o.name,0,yy);if(r>34){const mf=Math.max(8,fs*.55);ctx.font=`700 ${mf}px Arial`;ctx.strokeText(Math.round(c.mass),0,fs*.58);ctx.fillText(Math.round(c.mass),0,fs*.58)}}ctx.restore();
}

export function renderWorld(ctx,world,camera,w,h,dark=false){
  drawGrid(ctx,world,camera,w,h,dark);drawHotZones(ctx,world,camera,w,h);drawSafeZone(ctx,world,camera,w,h);drawClouds(ctx,world,camera,w,h);
  drawFood(ctx,world,camera,w,h);world.viruses.forEach(v=>drawVirus(ctx,world,camera,w,h,v));world.spawners.forEach(s=>drawSpawner(ctx,camera,w,h,s));world.mothers.forEach(m=>drawMother(ctx,camera,w,h,m));world.portals.forEach(p=>drawPortal(ctx,camera,w,h,p));world.bumpers.forEach(b=>drawBumper(ctx,camera,w,h,b));world.comets.forEach(c=>drawComet(ctx,camera,w,h,c));drawBossFragments(ctx,world,camera,w,h);drawEjected(ctx,world,camera,w,h);
  world.entities.filter(c=>c.alive).slice().sort((a,b)=>a.mass-b.mass).forEach(c=>drawCell(ctx,world,camera,w,h,c));
}
function drawClouds(ctx,world,camera,w,h){world.clouds.forEach(c=>drawCloud(ctx,camera,w,h,c));}

export function renderMini(mctx,canvas,world,dark=false){
  const r=canvas.getBoundingClientRect(),mw=Math.max(1,r.width),mh=Math.max(1,r.height),d=Math.min(2,devicePixelRatio||1),pw=Math.round(mw*d),ph=Math.round(mh*d);if(canvas.width!==pw||canvas.height!==ph){canvas.width=pw;canvas.height=ph;mctx.setTransform(d,0,0,d,0,0)}
  mctx.fillStyle=dark?'#1b2128':'#f5f5f5';mctx.fillRect(0,0,mw,mh);mctx.strokeStyle=dark?'#ffffff35':'#bbb';mctx.strokeRect(.5,.5,mw-1,mh-1);const sx=mw/world.size,sy=mh/world.size;
  if(world.safeZone){mctx.strokeStyle='#ec6469';mctx.lineWidth=1.5;mctx.beginPath();mctx.arc(world.safeZone.x*sx,world.safeZone.y*sy,world.safeZone.r*sx,0,6.28);mctx.stroke();}
  for(const z of world.hotZones){mctx.strokeStyle='#e8ad4e';mctx.beginPath();mctx.arc(z.x*sx,z.y*sy,z.r*sx,0,6.28);mctx.stroke();}
  for(const s of world.spawners){mctx.fillStyle='#e64c58';mctx.beginPath();mctx.arc(s.x*sx,s.y*sy,2.4,0,6.28);mctx.fill()}
  for(const p of world.portals){mctx.fillStyle='#a578ed';mctx.beginPath();mctx.arc(p.x*sx,p.y*sy,2,0,6.28);mctx.fill()}
  for(const o of world.bots)if(o.alive){const c=center(o);mctx.fillStyle=world.mode.teams?TEAM_DEFS[o.team].color:(dark?'#ffffff55':'#6668');mctx.beginPath();mctx.arc(c.x*sx,c.y*sy,1.6,0,6.28);mctx.fill()}
  const boss=world.bossState?.bossOwner;if(boss?.alive){const c=center(boss);mctx.fillStyle=boss.color;mctx.beginPath();mctx.arc(c.x*sx,c.y*sy,4.5,0,6.28);mctx.fill()}
  if(world.player?.alive){const c=center(world.player);mctx.fillStyle=world.player.color;mctx.beginPath();mctx.arc(c.x*sx,c.y*sy,4,0,6.28);mctx.fill();mctx.strokeStyle=dark?'#fff':'#333';mctx.stroke();}
}
