import {RARITY_COLORS,REGIONS,SPOTS,FISH,PROPERTY_POOL,LINES,BOOSTERS,PEARLS,ACCESSORIES,CHESTS,MISSION_DEFS} from "./ParadiseAnglerData.js";
import {
  loadState,saveState,refillEnergy,energyCountdown,fmt,xpNeed,selectSpot,selectLine,selectLure,buyLure,buyLine,toggleBooster,
  gearName,gearStats,equipGear,powerUpPreview,powerUpGear,evolvePreview,evolveGear,transcendPreview,transcendGear,
  repairGearPreview,repairGear,socketPearl,upgradeAccessory,equipAccessory,getCombatStats,getLureInfo,
  rollChest,chestOddsText,claimMission,uniqueSpecies,tankMaturity,storeFish,sellTankFish,expandTank,unlockLuresForLevel
} from "./ParadiseAnglerEngine.js";
import {createFishingSession,updateFishing,pressMain,setReeling,usePower,useFever,yank} from "./ParadiseAnglerFishing.js";
import {renderFishing} from "./ParadiseAnglerRender.js";

export default {
  manifest:{
    id:"paradise-angler",name:"Paradise Angler",
    description:"Deep arcade fishing RPG with tension battles, evolving rods and reels, tackle loot, fish tanks and worldwide fishing spots.",
    icon:"🎣",tags:["Fishing","RPG","Loot","Arcade","Progression"]
  },
  init:(container,services)=>{
    let destroyed=false,raf=0,last=performance.now(),saveTimer=0,uiTimer=0;
    let state=loadState();unlockLuresForLevel(state);refillEnergy(state);
    let screen="home",session=null,selectedGearUid=state.equippedRod,resultShown=false;
    let canvas=null,ctx=null,W=1,H=1,dpr=1,ro=null;

    const style=document.createElement("style");
    style.textContent=`
      .pa{position:relative;width:100%;height:100%;min-height:610px;overflow:hidden;background:#071827;color:#edf8fb;font-family:Inter,system-ui,-apple-system,"Segoe UI",sans-serif;user-select:none}
      .pa *{box-sizing:border-box}.pa button,.pa select{font:inherit}.pa button:disabled{opacity:.34;cursor:not-allowed}
      .pa-top{position:absolute;z-index:15;left:0;right:0;top:0;height:76px;display:grid;grid-template-columns:220px 1fr 420px;gap:8px;align-items:center;padding:8px 13px;background:#07131ee9;border-bottom:1px solid #7be7ff22;backdrop-filter:blur(9px)}
      .pa-brand{display:flex;align-items:center;gap:9px}.pa-logo{width:43px;height:43px;border-radius:11px;display:grid;place-items:center;background:linear-gradient(145deg,#136b82,#19436a);border:1px solid #7be7ff42;font-size:1.35rem}.pa-brand b{font-size:.9rem}.pa-brand small{display:block;color:#718c9b;font-size:.51rem}
      .pa-level{text-align:center}.pa-level strong{font-size:1.05rem}.pa-xp{height:9px;max-width:390px;margin:4px auto;border-radius:99px;background:#263744;overflow:hidden}.pa-xp div{height:100%;background:linear-gradient(90deg,#5fd9bb,#56aee8)}.pa-level small{font-size:.52rem;color:#879ca6}
      .pa-cur{display:grid;grid-template-columns:repeat(4,1fr);gap:4px}.pa-c{padding:7px 4px;border-radius:7px;background:#102433;border:1px solid #ffffff0d;text-align:center;font-size:.55rem;font-weight:950}.pa-c.gold{color:#ffd55a}.pa-c.cash{color:#6ee8b7}.pa-c.energy{color:#78d9ff}.pa-c.key{color:#d5b5ff}
      .pa-body{position:absolute;inset:76px 0 0;display:grid;grid-template-columns:190px minmax(0,1fr);min-height:0}.pa-nav{background:#081722e8;border-right:1px solid #ffffff0d;padding:8px;overflow:auto}.pa-nav button{width:100%;padding:10px 9px;margin-bottom:5px;border:1px solid #ffffff0c;border-radius:8px;background:#0e2230;color:#839aa6;text-align:left;font-size:.58rem;font-weight:950;cursor:pointer}.pa-nav button.on{background:linear-gradient(90deg,#19485b,#133343);border-color:#61d8e55c;color:#fff}.pa-nav .sep{height:1px;background:#ffffff0b;margin:8px 0}
      .pa-main{position:relative;min-width:0;min-height:0;overflow:hidden;background:radial-gradient(circle at 50% 20%,#17445b66,transparent 42%),#07151f}.pa-page{height:100%;overflow:auto;padding:12px}.pa-heading{display:flex;align-items:end;justify-content:space-between;margin-bottom:10px}.pa-heading h2{margin:0;font-size:1.35rem}.pa-heading p{margin:3px 0 0;color:#758e9a;font-size:.58rem}.pa-chip{padding:6px 8px;border-radius:99px;background:#102635;border:1px solid #ffffff10;font-size:.53rem;color:#aac1ca}
      .pa-region{margin-bottom:13px}.pa-region h3{font-size:.72rem;margin:0 0 6px;color:var(--accent)}.pa-spots{display:grid;grid-template-columns:repeat(3,1fr);gap:7px}.pa-spot{min-height:120px;padding:10px;border:1px solid #ffffff10;border-radius:10px;background:linear-gradient(145deg,#102836,#0b1d28);cursor:pointer;position:relative;overflow:hidden}.pa-spot:hover:not(.locked){border-color:var(--accent)}.pa-spot.locked{opacity:.28;filter:grayscale(1);cursor:not-allowed}.pa-spot.selected{border-color:#72e6da;box-shadow:0 0 0 2px #58dbc433}.pa-spot b{font-size:.7rem}.pa-spot small{display:block;margin-top:3px;color:#78909b;font-size:.52rem;line-height:1.4}.pa-stars{color:#f3c95d!important;font-size:.57rem}.pa-secret{position:absolute;right:7px;top:7px;color:#c28aff;font-size:.49rem;font-weight:950}
      .pa-depart{margin-top:10px;display:grid;grid-template-columns:1fr 1fr 1.3fr;gap:7px}.pa-card{padding:10px;border:1px solid #ffffff0f;border-radius:9px;background:#0d202c}.pa-card h3{font-size:.62rem;margin:0 0 7px}.pa-card p{font-size:.54rem;color:#8198a3;line-height:1.5}.pa-select{width:100%;padding:8px;border:1px solid #ffffff13;border-radius:7px;background:#091821;color:#eaf5f7;font-size:.57rem}.pa-boosts{display:flex;gap:5px;flex-wrap:wrap}.pa-boost{padding:7px;border:1px solid #ffffff12;border-radius:7px;background:#112633;color:#879ca6;font-size:.50rem;font-weight:900;cursor:pointer}.pa-boost.on{color:#fff;border-color:#75d8ee;background:#184052}.pa-fish-preview{display:flex;gap:5px}.pa-fish-pill{flex:1;text-align:center;padding:6px;border-radius:7px;background:#081821;font-size:.48rem}.pa-fish-pill span{display:block;color:#f1c75b;margin-top:3px}.pa-go{width:100%;margin-top:8px;padding:12px;border:0;border-radius:9px;background:linear-gradient(135deg,#6de4c7,#58b8ed);color:#06141a;font-weight:1000;cursor:pointer}
      .pa-gear-layout{display:grid;grid-template-columns:minmax(300px,1fr) minmax(300px,420px);gap:9px}.pa-grid{display:grid;grid-template-columns:repeat(3,1fr);gap:6px}.pa-gear{padding:8px;border:1px solid #ffffff0e;border-radius:8px;background:#0d202c;cursor:pointer;min-height:92px}.pa-gear.on{border-color:#6adce6}.pa-gear b{display:block;font-size:.58rem}.pa-gear small{display:block;color:#748b97;font-size:.48rem;margin-top:3px}.pa-grade{font-size:.55rem;color:#f0c75b;margin:3px 0}.pa-gear-detail h3{margin:0}.pa-stat{display:grid;grid-template-columns:1fr auto;gap:7px;padding:5px 0;border-bottom:1px solid #ffffff0a;font-size:.54rem}.pa-stat span{color:#8196a0}.pa-actions{display:grid;grid-template-columns:1fr 1fr;gap:5px;margin-top:8px}.pa-actions button{padding:8px;border:1px solid #ffffff12;border-radius:7px;background:#123042;color:#fff;font-size:.52rem;font-weight:900;cursor:pointer}.pa-props{margin-top:7px;padding:7px;border-radius:7px;background:#081821;font-size:.51rem;line-height:1.5}.pa-arrow{color:#7ee7b7;font-weight:1000}
      .pa-shop-grid{display:grid;grid-template-columns:repeat(4,1fr);gap:8px}.pa-chest{padding:13px;border:1px solid #ffffff10;border-radius:11px;background:linear-gradient(145deg,#132a38,#0b1923);text-align:center}.pa-chest .ico{font-size:2.2rem}.pa-chest b{display:block;font-size:.68rem;margin:5px}.pa-chest p{min-height:42px;color:#7c929c;font-size:.50rem;line-height:1.4}.pa-chest .odds{font-size:.48rem;color:#d5b7ef}.pa-chest button{width:100%;margin-top:8px;padding:9px;border:0;border-radius:7px;background:#26556a;color:#fff;font-size:.53rem;font-weight:950;cursor:pointer}.pa-market{display:grid;grid-template-columns:1fr 1fr;gap:8px;margin-top:12px}.pa-market-row{display:grid;grid-template-columns:1fr auto;gap:6px;align-items:center;padding:8px;border:1px solid #ffffff0e;border-radius:8px;background:#0c1e29}.pa-market-row b{font-size:.56rem}.pa-market-row small{display:block;font-size:.48rem;color:#748c97;margin-top:2px}.pa-market-row button{padding:7px;border:0;border-radius:6px;background:#1f4658;color:#fff;font-size:.50rem;cursor:pointer}
      .pa-book{display:grid;grid-template-columns:repeat(5,1fr);gap:6px}.pa-bookfish{min-height:90px;padding:8px;border:1px solid #ffffff0c;border-radius:8px;background:#0b1d28;text-align:center}.pa-bookfish.unknown{opacity:.26;filter:grayscale(1)}.pa-bookfish .fishico{font-size:1.5rem}.pa-bookfish b{display:block;font-size:.52rem;margin-top:4px}.pa-bookfish small{display:block;font-size:.45rem;color:#768e99;margin-top:2px}
      .pa-tank{display:grid;grid-template-columns:repeat(4,1fr);gap:7px}.pa-tankfish{padding:9px;border:1px solid #ffffff0f;border-radius:8px;background:#0c1f2a}.pa-tankfish b{font-size:.55rem}.pa-tankfish small{display:block;color:#7e959f;font-size:.47rem;margin-top:3px}.pa-mature{height:6px;background:#233642;border-radius:99px;margin:7px 0;overflow:hidden}.pa-mature div{height:100%;background:linear-gradient(90deg,#59b9ee,#64dfae)}.pa-tankfish button{width:100%;padding:6px;border:0;border-radius:5px;background:#1b4354;color:#fff;font-size:.48rem;cursor:pointer}.pa-missions{display:grid;grid-template-columns:repeat(2,1fr);gap:7px}.pa-mission{padding:10px;border:1px solid #ffffff0e;border-radius:8px;background:#0c1f2a}.pa-mission b{font-size:.6rem}.pa-mission small{display:block;font-size:.49rem;color:#7f959f;margin:3px 0}.pa-progress{height:7px;background:#22343e;border-radius:99px;overflow:hidden;margin:7px 0}.pa-progress div{height:100%;background:#66d9b2}.pa-mission button{padding:7px 10px;border:0;border-radius:6px;background:#26614e;color:#fff;font-size:.48rem;font-weight:900;cursor:pointer}
      .pa-fishing{position:absolute;inset:0;z-index:20;background:#071722}.pa-fishing canvas{width:100%;height:100%;display:block}.pa-controls{position:absolute;left:50%;bottom:12px;transform:translateX(-50%);display:flex;gap:7px;align-items:center}.pa-control{min-width:110px;height:48px;border:0;border-radius:11px;background:#e7eef0;color:#0a1720;font-weight:1000;cursor:pointer;box-shadow:0 8px 25px #0005}.pa-control.reel{min-width:180px;background:linear-gradient(135deg,#64ddc0,#56b4eb)}.pa-control.power{background:#5ba8e3;color:#fff}.pa-control.fever{background:#c069c6;color:#fff}.pa-yanks{position:absolute;left:50%;bottom:74px;transform:translateX(-50%);display:flex;gap:170px}.pa-yanks button{width:72px;height:45px;border:1px solid #ffffff24;border-radius:9px;background:#0b1c28cf;color:#fff;font-size:1.25rem;cursor:pointer}.pa-back{position:absolute;z-index:25;left:10px;top:10px;border:1px solid #ffffff16;border-radius:7px;background:#071722ce;color:#fff;padding:7px 9px;font-size:.52rem;cursor:pointer}
      .pa-modal{position:absolute;z-index:50;inset:0;background:#02080ddc;display:flex;align-items:center;justify-content:center;padding:18px;backdrop-filter:blur(8px)}.pa-modal-card{width:min(720px,96%);max-height:90%;overflow:auto;padding:18px;border-radius:13px;background:linear-gradient(#132b38,#081720);border:1px solid #6adee844;box-shadow:0 35px 100px #000a}.pa-modal-card h2{margin:0 0 5px}.pa-modal-card p{font-size:.57rem;color:#849aa4}.pa-resultfish{text-align:center;padding:14px}.pa-resultfish .big{font-size:3rem}.pa-resultfish h2{color:var(--rc)}.pa-rewards{display:grid;grid-template-columns:repeat(4,1fr);gap:6px;margin:9px 0}.pa-reward{padding:8px;border-radius:7px;background:#091923;text-align:center}.pa-reward small{display:block;color:#718993;font-size:.46rem}.pa-modal-actions{display:flex;gap:6px}.pa-modal-actions button{flex:1;padding:9px;border:0;border-radius:7px;background:#1e5063;color:#fff;font-size:.54rem;font-weight:950;cursor:pointer}
      @media(max-width:1080px){.pa-top{grid-template-columns:155px 1fr 330px}.pa-body{grid-template-columns:150px minmax(0,1fr)}.pa-nav button{padding:8px 6px}.pa-spots{grid-template-columns:1fr 1fr}.pa-shop-grid{grid-template-columns:1fr 1fr}.pa-grid{grid-template-columns:1fr 1fr}.pa-book{grid-template-columns:repeat(4,1fr)}.pa-tank{grid-template-columns:repeat(3,1fr)}}
      @media(max-width:820px){.pa{min-height:520px}.pa-top{height:64px;grid-template-columns:1fr 1.8fr}.pa-brand{display:none}.pa-body{inset:64px 0 0;grid-template-columns:118px minmax(0,1fr)}.pa-nav{padding:4px}.pa-nav button{font-size:.49rem}.pa-cur{gap:2px}.pa-c{padding:5px 2px;font-size:.48rem}.pa-level strong{font-size:.82rem}.pa-page{padding:7px}.pa-depart{grid-template-columns:1fr}.pa-gear-layout{grid-template-columns:1fr}.pa-shop-grid,.pa-market,.pa-missions{grid-template-columns:1fr}.pa-book{grid-template-columns:repeat(3,1fr)}.pa-tank{grid-template-columns:repeat(2,1fr)}}
      @media(max-height:680px){.pa{min-height:480px}.pa-top{height:60px}.pa-body{inset:60px 0 0}.pa-spot{min-height:92px;padding:7px}.pa-heading{margin-bottom:6px}.pa-heading h2{font-size:1rem}.pa-controls{bottom:6px}.pa-control{height:40px}.pa-control.reel{min-width:150px}}
    `;

    const root=document.createElement("div");root.className="pa";
    root.innerHTML=`<header class="pa-top"><div class="pa-brand"><div class="pa-logo">🎣</div><div><b>PARADISE ANGLER</b><small>Arcade Fishing RPG</small></div></div><div class="pa-level"></div><div class="pa-cur"></div></header>
      <div class="pa-body"><nav class="pa-nav"><button data-screen="home">🌊 FISH</button><button data-screen="gear">🎣 TACKLE</button><button data-screen="shop">🧰 SHOP & CHESTS</button><div class="sep"></div><button data-screen="book">📖 FISH BOOK</button><button data-screen="tank">🐠 FISH TANK</button><button data-screen="missions">✓ MISSIONS</button><button data-screen="practice">🎯 PRACTICE ROOM</button></nav><main class="pa-main"></main></div><div class="pa-modal-host"></div>`;
    container.append(style,root);
    const main=root.querySelector(".pa-main"),levelEl=root.querySelector(".pa-level"),curEl=root.querySelector(".pa-cur"),host=root.querySelector(".pa-modal-host");

    function top(){
      refillEnergy(state);unlockLuresForLevel(state);const need=xpNeed(state.level),pct=Math.min(100,state.xp/need*100),ms=energyCountdown(state),sec=Math.ceil(ms/1000);
      levelEl.innerHTML=`<strong>LEVEL ${state.level}</strong><div class="pa-xp"><div style="width:${pct}%"></div></div><small>${fmt(state.xp)} / ${fmt(need)} XP · ${uniqueSpecies(state)} species</small>`;
      curEl.innerHTML=`<div class="pa-c gold">● ${fmt(state.gold)}</div><div class="pa-c cash">◆ ${fmt(state.cash)}</div><div class="pa-c energy">⚡ ${state.energy}/${state.maxEnergy}${state.energy<state.maxEnergy?` · ${Math.floor(sec/60)}:${String(sec%60).padStart(2,"0")}`:""}</div><div class="pa-c key">▣ ${state.silverKey} · ◆ ${state.goldKey}</div>`;
    }
    function nav(){root.querySelectorAll("[data-screen]").forEach(b=>b.classList.toggle("on",b.dataset.screen===screen));}
    function heading(title,desc,chip=""){return `<div class="pa-heading"><div><h2>${title}</h2><p>${desc}</p></div>${chip?`<div class="pa-chip">${chip}</div>`:""}</div>`;}

    function renderHome(){
      const spot=SPOTS.find(x=>x.id===state.selectedSpot),combat=getCombatStats(state);
      main.innerHTML=`<div class="pa-page">${heading("WORLD FISHING","Choose a spot, prepare line/lure/boosters, then depart.",`Combined damage ${fmt(combat.damage)}`)}
        ${REGIONS.map(r=>`<section class="pa-region" style="--accent:${r.accent}"><h3>${r.name} · unlock Lv.${r.unlock}</h3><div class="pa-spots">${SPOTS.filter(s=>s.region===r.id).map(sp=>{const locked=state.level<sp.unlock,sel=state.selectedSpot===sp.id;return `<div class="pa-spot ${locked?"locked":""} ${sel?"selected":""}" style="--accent:${r.accent}" data-spot="${sp.id}">${sp.secret?`<span class="pa-secret">SECRET · ${sp.energy}⚡</span>`:""}<b>${sp.name}</b><small>${locked?`Requires Lv.${sp.unlock}`:`Difficulty ${sp.difficulty.toFixed(1)} · ${sp.energy} energy/cast`}</small><small class="pa-stars">Boss: ★★★★★ ${FISH[sp.boss].name}</small></div>`;}).join("")}</div></section>`).join("")}
        ${departPanel(spot)}</div>`;
      main.querySelectorAll("[data-spot]").forEach(el=>el.onclick=()=>{if(selectSpot(state,el.dataset.spot)){renderHome();saveState(state);}});bindDepart();
    }
    function departPanel(spot){
      const region=REGIONS.find(r=>r.id===spot.region),lureOptions=["common","rare","high","hidden"].map(t=>`${region.id}:${t}`).filter(k=>(state.inventory.lures[k]||0)>0),lineOptions=LINES.filter(l=>(state.inventory.lines[l.id]||0)>0),can=state.energy>=spot.energy&&lineOptions.length&&lureOptions.length;
      return `<div class="pa-depart"><div class="pa-card"><h3>LINE</h3><select class="pa-select line-select">${lineOptions.map(l=>`<option value="${l.id}" ${state.selectedLine===l.id?"selected":""}>${"★".repeat(l.stars)} ${l.name} ×${state.inventory.lines[l.id]} · ${l.length}m · tension ${l.tension}</option>`).join("")}</select></div>
        <div class="pa-card"><h3>LURE</h3><select class="pa-select lure-select">${lureOptions.map(k=>{const i=getLureInfo({...state,selectedLure:k});return `<option value="${k}" ${state.selectedLure===k?"selected":""}>${i.name} ×${state.inventory.lures[k]} · rare +${Math.round(i.rare*100)}% · big +${Math.round(i.big*100)}%</option>`;}).join("")}</select></div>
        <div class="pa-card"><h3>NEXT-CAST BOOSTERS</h3><div class="pa-boosts">${BOOSTERS.map(b=>`<button class="pa-boost ${state.activeBoosters[b.id]?"on":""}" data-boost="${b.id}">${b.icon} ${b.name} ×${state.inventory.boosters[b.id]||0}</button>`).join("")}</div></div>
        <div class="pa-card" style="grid-column:1/-1"><h3>FISH AT ${spot.name.toUpperCase()}</h3><div class="pa-fish-preview">${spot.fish.map(id=>{const f=FISH[id],known=state.fishBook[id]?.count;return `<div class="pa-fish-pill">${known?f.name:"?????"}<span>${"★".repeat(f.stars)}</span></div>`;}).join("")}</div><button class="pa-go" ${can?"":"disabled"} data-go="fish">CAST · ${spot.energy} ⚡</button></div></div>`;
    }
    function bindDepart(){
      main.querySelector(".line-select")?.addEventListener("change",e=>{selectLine(state,e.target.value);saveState(state);});main.querySelector(".lure-select")?.addEventListener("change",e=>{selectLure(state,e.target.value);saveState(state);});
      main.querySelectorAll("[data-boost]").forEach(b=>b.onclick=()=>{toggleBooster(state,b.dataset.boost);renderHome();});main.querySelector('[data-go="fish"]')?.addEventListener("click",()=>startFishing(false));
    }

    function renderGear(){
      const gear=state.inventory.gear,sel=gear.find(g=>g.uid===selectedGearUid)||gear[0];selectedGearUid=sel?.uid;
      main.innerHTML=`<div class="pa-page">${heading("TACKLE BOX","Rod + Reel damage, properties, pearls, power-up, evolution and transcendence.",`Power Stones ${state.powerStone} · Evo ${state.evoStone} · Coral ${state.coral}`)}
        <div class="pa-gear-layout"><div class="pa-grid">${gear.map(g=>{const st=gearStats(g),eq=state.equippedRod===g.uid||state.equippedReel===g.uid;return `<div class="pa-gear ${sel?.uid===g.uid?"on":""}" data-g="${g.uid}"><b>${gearName(g)}</b><div class="pa-grade">${"★".repeat(g.stars)} +${g.plus}${g.transcend?` · T${g.transcend}`:""}</div><small>${g.type.toUpperCase()} · ${fmt(st.damage)} damage</small><small>Condition ${g.durability}/${g.maxDurability}${eq?" · EQUIPPED":""}</small></div>`;}).join("")}</div><div class="pa-card pa-gear-detail">${sel?gearDetail(sel):"No equipment."}</div></div>
        <div class="pa-market"><div class="pa-card"><h3>PEARLS</h3>${PEARLS.map(p=>`<div class="pa-stat"><span style="color:${p.color}">● ${p.name} · +${p.value}${PROPERTY_POOL.find(x=>x.id===p.property)?.unit||"%"}</span><b>×${state.inventory.pearls[p.id]||0}</b></div>`).join("")}</div>
        <div class="pa-card"><h3>ACCESSORY</h3>${ACCESSORIES.map(a=>{const lv=state.inventory.accessories[a.id]||0;return `<div class="pa-market-row"><div><b>${"★".repeat(a.stars)} ${a.name}</b><small>${lv?`Lv ${lv} · Crit ${a.critRate}% · Crit DMG ${a.critDamage}% · Accuracy ${a.accuracy}`:"Not owned"}</small></div><button data-acc="${a.id}" ${lv?"":"disabled"}>${state.equippedAccessory===a.id?"UPGRADE":"EQUIP"}</button></div>`;}).join("")}</div></div></div>`;
      main.querySelectorAll("[data-g]").forEach(el=>el.onclick=()=>{selectedGearUid=el.dataset.g;renderGear();});bindGear(sel);
      main.querySelectorAll("[data-acc]").forEach(el=>el.onclick=()=>{const id=el.dataset.acc;if(state.equippedAccessory===id)upgradeAccessory(state,id);else equipAccessory(state,id);renderGear();saveState(state);});
    }
    function gearDetail(g){
      const st=gearStats(g),pp=powerUpPreview(state,g.uid),ev=evolvePreview(state,g.uid),tr=transcendPreview(state,g.uid),rp=repairGearPreview(state,g.uid),eq=(state.equippedRod===g.uid||state.equippedReel===g.uid),propText=g.properties.length?g.properties.map(p=>{const d=PROPERTY_POOL.find(x=>x.id===p.id);return `${d?.name||p.id} +${p.value}${d?.unit||"%"}`;}).join("<br>"):"No bonus properties yet.";
      return `<h3>${gearName(g)}</h3><div class="pa-grade">${"★".repeat(g.stars)} · +${g.plus} ${g.transcend?`· Transcend ${g.transcend}`:""}</div><div class="pa-stat"><span>Damage</span><b>${fmt(st.damage)}</b></div><div class="pa-stat"><span>Condition</span><b>${g.durability}/${g.maxDurability}</b></div><div class="pa-props">${propText}</div><div class="pa-stat"><span>Pearl Slot 1</span><b>${g.pearls[0]||"Empty"}</b></div><div class="pa-stat"><span>Pearl Slot 2</span><b>${g.pearls[1]||"Empty"}</b></div>
        ${pp?`<div class="pa-props"><b>POWER-UP +${g.plus} → +${g.plus+1}</b><br>Damage ${fmt(pp.before)} → <span class="pa-arrow">${fmt(pp.after)}</span><br>Cost ● ${fmt(pp.costGold)} + ${pp.stones} Power Stones</div>`:""}${ev?`<div class="pa-props"><b>EVOLVE ${g.stars}★ → ${g.stars+1}★</b><br>Damage ${fmt(ev.before)} → <span class="pa-arrow">${fmt(ev.after)}</span><br>Cost ● ${fmt(ev.gold)} + ${ev.evo} Evo Stones</div>`:""}${tr?`<div class="pa-props"><b>TRANSCEND T${g.transcend} → T${g.transcend+1}</b><br>Damage ${fmt(tr.before)} → <span class="pa-arrow">${fmt(tr.after)}</span><br>Success ${(tr.chance*100).toFixed(0)}% · ◆${tr.cash} + ⬡${tr.coral}</div>`:""}
        <div class="pa-actions"><button data-act="equip">${eq?"EQUIPPED":"EQUIP"}</button><button data-act="power" ${pp?"":"disabled"}>POWER-UP</button><button data-act="evolve" ${ev?"":"disabled"}>EVOLVE</button><button data-act="trans" ${tr?"":"disabled"}>TRANSCEND</button><button data-act="repair" ${rp?"":"disabled"}>${rp?`REPAIR · ●${fmt(rp.cost)}`:"FULL CONDITION"}</button><button data-act="pearl">SOCKET PEARL</button></div>`;
    }
    function bindGear(g){
      if(!g)return;main.querySelector('[data-act="equip"]')?.addEventListener("click",()=>{equipGear(state,g.uid);renderGear();saveState(state);});main.querySelector('[data-act="power"]')?.addEventListener("click",()=>{powerUpGear(state,g.uid);renderGear();saveState(state);});main.querySelector('[data-act="evolve"]')?.addEventListener("click",()=>{evolveGear(state,g.uid);renderGear();saveState(state);});
      main.querySelector('[data-act="trans"]')?.addEventListener("click",()=>{const r=transcendGear(state,g.uid);showToast(r?.success?"TRANSCEND SUCCESS!":r?.ok?"TRANSCEND FAILED":"Not enough materials");renderGear();saveState(state);});main.querySelector('[data-act="repair"]')?.addEventListener("click",()=>{repairGear(state,g.uid);renderGear();saveState(state);});main.querySelector('[data-act="pearl"]')?.addEventListener("click",()=>pearlModal(g));
    }
    function pearlModal(g){
      showModal("SOCKET PEARL",`Choose a pearl for ${gearName(g)}. Replaced pearls return to inventory.`,`<div class="pa-market">${PEARLS.map(p=>`<div class="pa-market-row"><div><b style="color:${p.color}">● ${p.name}</b><small>+${p.value}${PROPERTY_POOL.find(x=>x.id===p.property)?.unit||"%"} ${PROPERTY_POOL.find(x=>x.id===p.property)?.name||p.property} · owned ${state.inventory.pearls[p.id]||0}</small></div><button data-p="${p.id}" ${(state.inventory.pearls[p.id]||0)<=0?"disabled":""}>SOCKET</button></div>`).join("")}</div>`);
      host.querySelectorAll("[data-p]").forEach(el=>el.onclick=()=>{const slot=g.pearls[0]?g.pearls[1]?0:1:0;if(socketPearl(state,g.uid,slot,el.dataset.p)){closeModal();renderGear();saveState(state);}});
    }

    function renderShop(){
      const region=REGIONS.find(r=>r.id===(SPOTS.find(x=>x.id===state.selectedSpot)?.region||"hawaii"));
      main.innerHTML=`<div class="pa-page">${heading("SHOP & LOOT CHESTS","Chests disclose equipment-star odds. Browser build uses only earned in-game currency.",`Power ${state.powerStone} · Evo ${state.evoStone} · Pearl Powder ${state.pearlPowder}`)}<div class="pa-shop-grid">${CHESTS.map(c=>`<div class="pa-chest"><div class="ico">${c.icon}</div><b>${c.name}</b><p>${c.desc}</p><div class="odds">${chestOddsText(c)}</div><button data-chest="${c.id}">OPEN · ${Object.entries(c.open).map(([k,v])=>`${k==="gold"?"●":k==="cash"?"◆":"▣"} ${fmt(v)}`).join(" ")}</button></div>`).join("")}</div>
        <div class="pa-market"><div class="pa-card"><h3>LINES</h3>${LINES.filter(l=>!l.lootOnly).map(l=>`<div class="pa-market-row"><div><b>${"★".repeat(l.stars)} ${l.name}</b><small>${l.length}m · tension ${l.tension} · damage ${l.damage.toFixed(2)}× · owned ${state.inventory.lines[l.id]||0}</small></div><button data-linebuy="${l.id}">×5 · ●${fmt(l.costGold*5)}</button></div>`).join("")}</div>
        <div class="pa-card"><h3>${region.name.toUpperCase()} LURES</h3>${["common","rare","high"].map(t=>{const k=`${region.id}:${t}`,i=getLureInfo({...state,selectedLure:k});return `<div class="pa-market-row"><div><b>${i.name}</b><small>Rare +${Math.round(i.rare*100)}% · Big +${Math.round(i.big*100)}% · owned ${state.inventory.lures[k]||0}</small></div><button data-lurebuy="${k}">×5 · ●${fmt(i.cost*5)}</button></div>`;}).join("")}</div>
        <div class="pa-card"><h3>BOOSTERS</h3>${BOOSTERS.map(b=>`<div class="pa-market-row"><div><b>${b.icon} ${b.name}</b><small>${b.desc} · owned ${state.inventory.boosters[b.id]||0}</small></div><button data-boostbuy="${b.id}">×3 · ◆8</button></div>`).join("")}</div>
        <div class="pa-card"><h3>MATERIAL EXCHANGE</h3><div class="pa-market-row"><div><b>Power Stones ×25</b><small>Rod/Reel Power-Up material.</small></div><button data-mat="power">●6000</button></div><div class="pa-market-row"><div><b>Evo Stone ×2</b><small>Evolution after +10.</small></div><button data-mat="evo">◆18</button></div><div class="pa-market-row"><div><b>Pearl Powder ×60</b><small>Accessory Power-Up material.</small></div><button data-mat="powder">◆12</button></div></div></div></div>`;
      main.querySelectorAll("[data-chest]").forEach(el=>el.onclick=()=>{const r=rollChest(state,el.dataset.chest);if(r){lootModal(r);saveState(state);top();}else showToast("Not enough currency");});
      main.querySelectorAll("[data-linebuy]").forEach(el=>el.onclick=()=>{if(buyLine(state,el.dataset.linebuy,5)){renderShop();saveState(state);}});main.querySelectorAll("[data-lurebuy]").forEach(el=>el.onclick=()=>{const [reg,tier]=el.dataset.lurebuy.split(":");if(buyLure(state,reg,tier,5)){renderShop();saveState(state);}});
      main.querySelectorAll("[data-boostbuy]").forEach(el=>el.onclick=()=>{if(state.cash>=8){state.cash-=8;state.inventory.boosters[el.dataset.boostbuy]=(state.inventory.boosters[el.dataset.boostbuy]||0)+3;renderShop();saveState(state);}});main.querySelectorAll("[data-mat]").forEach(el=>el.onclick=()=>{const k=el.dataset.mat;if(k==="power"&&state.gold>=6000){state.gold-=6000;state.powerStone+=25;}if(k==="evo"&&state.cash>=18){state.cash-=18;state.evoStone+=2;}if(k==="powder"&&state.cash>=12){state.cash-=12;state.pearlPowder+=60;}renderShop();saveState(state);});
    }
    function lootModal(r){
      let title="Reward",detail="";if(r.loot.type==="gear"){const g=r.result;title=`${g.stars}★ ${gearName(g)}`;detail=`${g.type.toUpperCase()} · ${fmt(gearStats(g).damage)} damage · ${g.properties.length} bonus properties`;}else if(r.loot.type==="line"){const l=LINES.find(x=>x.id===r.loot.id);title=`${l.name} ×${r.loot.count}`;detail=`${l.length}m · tension ${l.tension} · damage ${l.damage.toFixed(2)}×`;}else if(r.loot.type==="pearl"){const p=PEARLS.find(x=>x.id===r.loot.id);title=p.name;detail=`Socketable pearl · +${p.value} ${p.property}`;}else if(r.loot.type==="accessory"){const a=ACCESSORIES.find(x=>x.id===r.loot.id);title=a.name;detail=`Accessory · Crit ${a.critRate}% · Crit Damage +${a.critDamage}%`;}else title=`${r.loot.type} ×${r.loot.count||1}`;
      showModal(r.chest.name,"LOOT REVEAL",`<div class="pa-resultfish"><div class="big">${r.chest.icon}</div><h2>${title}</h2><p>${detail}</p></div><div class="pa-modal-actions"><button data-close>KEEP</button></div>`);host.querySelector("[data-close]").onclick=()=>{closeModal();renderShop();};
    }

    function renderBook(){
      main.innerHTML=`<div class="pa-page">${heading("FISH BOOK","Catch count and personal-best weight are stored for every species.",`${uniqueSpecies(state)} / ${Object.keys(FISH).length} discovered`)}${REGIONS.map(r=>{const ids=[...new Set(SPOTS.filter(s=>s.region===r.id).flatMap(s=>s.fish))];return `<section class="pa-region"><h3 style="color:${r.accent}">${r.name}</h3><div class="pa-book">${ids.map(id=>{const f=FISH[id],e=state.fishBook[id],known=e?.count>0;return `<div class="pa-bookfish ${known?"":"unknown"}"><div class="fishico">🐟</div><b>${known?f.name:"?????"}</b><small style="color:${RARITY_COLORS[f.stars]}">${known?"★".repeat(f.stars):"Unknown"}</small><small>${known?`Caught ×${e.count} · Best ${e.best.toFixed(2)} kg`:"Catch it to register."}</small></div>`;}).join("")}</div></section>`;}).join("")}</div>`;
    }
    function renderTank(){
      const now=Date.now(),expandCost=5000*Math.pow(1.85,Math.floor((state.tankCap-20)/10));main.innerHTML=`<div class="pa-page">${heading("FISH TANK","Stored fish mature in real time. Fully grown boss fish can return premium Cash.",`${state.tank.length}/${state.tankCap} slots`)}<div class="pa-modal-actions" style="max-width:280px;margin-bottom:9px"><button data-expand>EXPAND +10 · ●${fmt(expandCost)}</button></div><div class="pa-tank">${state.tank.length?state.tank.map(item=>{const f=FISH[item.fishId],m=tankMaturity(item,now),gold=Math.round(f.value*(.9+item.weight/f.weight[1])*(1+m*.9));return `<div class="pa-tankfish"><b>${"★".repeat(f.stars)} ${f.name}</b><small>${item.weight.toFixed(2)} kg · ${m>=1?"FULLY GROWN":`${Math.floor(m*100)}% grown`}</small><div class="pa-mature"><div style="width:${m*100}%"></div></div><small>Sell: ●${fmt(gold)}${f.boss&&m>=1?" + premium Cash":""}</small><button data-sell="${item.id}">SELL</button></div>`;}).join(""):`<div class="pa-card">No fish stored yet. After a catch choose <b>STORE IN TANK</b>.</div>`}</div></div>`;
      main.querySelector("[data-expand]")?.addEventListener("click",()=>{if(expandTank(state)){renderTank();saveState(state);}});main.querySelectorAll("[data-sell]").forEach(el=>el.onclick=()=>{sellTankFish(state,el.dataset.sell);renderTank();saveState(state);});
    }
    function renderMissions(){
      main.innerHTML=`<div class="pa-page">${heading("MISSIONS","Goals feed keys, Cash and materials back into the fishing-progression loop.")}<div class="pa-missions">${MISSION_DEFS.map(d=>{const m=state.missions[d.id],pct=Math.min(100,m.progress/d.target*100),reward=Object.entries(d.reward).map(([k,v])=>`${k}: ${v}`).join(" · ");return `<div class="pa-mission"><b>${d.name}</b><small>${d.type.toUpperCase()} · ${m.progress}/${d.target}</small><div class="pa-progress"><div style="width:${pct}%"></div></div><small>Reward: ${reward}</small><button data-m="${d.id}" ${m.claimed||m.progress<d.target?"disabled":""}>${m.claimed?"CLAIMED":"CLAIM"}</button></div>`;}).join("")}</div></div>`;
      main.querySelectorAll("[data-m]").forEach(el=>el.onclick=()=>{if(claimMission(state,el.dataset.m)){renderMissions();saveState(state);}});
    }
    function renderPractice(){const st=getCombatStats(state);main.innerHTML=`<div class="pa-page">${heading("PRACTICE ROOM","No Energy, lure or line is consumed. Rewards are disabled.",`Damage ${fmt(st.damage)} · Tension ${Math.round(st.tension)}`)}<div class="pa-card"><h3>Training setup</h3><p>Practice uses your selected spot and equipped tackle. Cast timing, tension control, yanks, Power Pull and Fever are identical to a normal battle.</p><button class="pa-go" data-practice>START PRACTICE</button></div></div>`;main.querySelector("[data-practice]").onclick=()=>startFishing(true);}

    function startFishing(practice){
      session=createFishingSession(state,{practice});if(!session){showToast("Need Energy, Line and Lure");return;}screen="fishing";nav();resultShown=false;
      main.innerHTML=`<div class="pa-fishing"><canvas></canvas><button class="pa-back">ABANDON</button><div class="pa-yanks"><button data-yank="left">←</button><button data-yank="right">→</button></div><div class="pa-controls"><button class="pa-control main">CAST</button><button class="pa-control reel">HOLD TO REEL</button><button class="pa-control power">POWER</button><button class="pa-control fever">FEVER</button></div></div>`;
      canvas=main.querySelector("canvas");ctx=canvas.getContext("2d");const resize=()=>{const r=canvas.getBoundingClientRect();W=Math.max(1,r.width);H=Math.max(1,r.height);dpr=Math.min(2,devicePixelRatio||1);canvas.width=Math.round(W*dpr);canvas.height=Math.round(H*dpr);ctx.setTransform(dpr,0,0,dpr,0,0);};ro?.disconnect();ro=new ResizeObserver(resize);ro.observe(canvas);resize();
      const mainBtn=main.querySelector(".main"),reelBtn=main.querySelector(".reel"),powerBtn=main.querySelector(".power"),feverBtn=main.querySelector(".fever");mainBtn.onclick=()=>pressMain(session,state);reelBtn.onpointerdown=e=>{e.preventDefault();setReeling(session,true);};reelBtn.onpointerup=e=>{e.preventDefault();setReeling(session,false);};reelBtn.onpointerleave=()=>setReeling(session,false);powerBtn.onclick=()=>usePower(session);feverBtn.onclick=()=>useFever(session);main.querySelectorAll("[data-yank]").forEach(b=>b.onclick=()=>yank(session,b.dataset.yank));main.querySelector(".pa-back").onclick=()=>{session=null;screen="home";renderScreen();};top();
    }
    function updateFishingControls(){
      if(!session||screen!=="fishing")return;const mainBtn=main.querySelector(".main"),reel=main.querySelector(".reel"),power=main.querySelector(".power"),fever=main.querySelector(".fever"),yanks=main.querySelector(".pa-yanks");
      if(mainBtn){mainBtn.style.display=["cast","bite"].includes(session.phase)?"block":"none";mainBtn.textContent=session.phase==="cast"?"CAST":"HOOK!";}if(reel)reel.style.display=session.phase==="fight"?"block":"none";if(power){power.style.display=session.phase==="fight"?"block":"none";power.disabled=session.power<99;}if(fever){fever.style.display=session.phase==="fight"?"block":"none";fever.disabled=session.fever<99||session.feverTime>0;}if(yanks)yanks.style.display=session.phase==="fight"&&session.jump?"flex":"none";if(session.phase==="result"&&(session.result||session.failed))finishFishingModal();
    }
    function finishFishingModal(){
      if(resultShown)return;resultShown=true;
      if(session.failed)showModal("THE FISH ESCAPED",session.failReason,`<div class="pa-resultfish"><div class="big">〰</div><p>Watch line tension, line length and when to release the reel.</p></div><div class="pa-modal-actions"><button data-home>BACK TO WATER</button><button data-again>TRY AGAIN</button></div>`);
      else{const r=session.result,f=FISH[r.fishId],rw=r.reward;showModal(r.practice?"PRACTICE CATCH":`${rw.grade} GRADE CATCH`,`${session.castGrade} CAST`,`<div class="pa-resultfish" style="--rc:${RARITY_COLORS[f.stars]}"><div class="big">🐟</div><h2>${"★".repeat(f.stars)} ${f.name}</h2><p>${r.weight.toFixed(2)} kg ${f.boss?"· BOSS FISH":""}</p></div><div class="pa-rewards"><div class="pa-reward"><small>GOLD</small><b>● ${fmt(rw.gold)}</b></div><div class="pa-reward"><small>XP</small><b>✦ ${fmt(rw.xp)}</b></div><div class="pa-reward"><small>GRADE</small><b>${rw.grade}</b></div><div class="pa-reward"><small>EXTRAS</small><b>${rw.extras?.join(", ")||"—"}</b></div></div><div class="pa-modal-actions"><button data-home>CONTINUE</button>${r.practice?"":`<button data-store>STORE IN TANK</button>`}<button data-again>${r.practice?"PRACTICE AGAIN":"CAST AGAIN"}</button></div>`);}
      host.querySelector("[data-home]")?.addEventListener("click",()=>{closeModal();session=null;screen="home";resultShown=false;renderScreen();saveState(state);});host.querySelector("[data-again]")?.addEventListener("click",()=>{const practice=session?.practice;closeModal();session=null;resultShown=false;screen="home";renderScreen();setTimeout(()=>startFishing(practice),0);});host.querySelector("[data-store]")?.addEventListener("click",e=>{if(storeFish(state,session.result)){e.currentTarget.disabled=true;e.currentTarget.textContent="STORED";saveState(state);showToast("Stored in Fish Tank");}else showToast("Fish Tank is full");});
      if(session.result&&!session.result.practice){const score=Math.round((session.result.weight||0)*100+state.stats.bosses*1000+uniqueSpecies(state)*50);services?.highscores?.saveHighscore?.("paradise-angler",score);}
    }

    function showModal(title,sub,body){host.innerHTML=`<div class="pa-modal"><div class="pa-modal-card"><h2>${title}</h2><p>${sub}</p>${body}</div></div>`;}
    function closeModal(){host.innerHTML="";}
    function showToast(text){const d=document.createElement("div");d.style.cssText="position:absolute;z-index:80;left:50%;top:86px;transform:translateX(-50%);padding:9px 13px;border-radius:8px;background:#102b37ef;border:1px solid #66d9dd55;color:#fff;font-size:.58rem;font-weight:900;box-shadow:0 10px 30px #0007";d.textContent=text;root.append(d);setTimeout(()=>d.remove(),1700);}
    function renderScreen(){nav();top();resultShown=false;if(screen==="home")renderHome();else if(screen==="gear")renderGear();else if(screen==="shop")renderShop();else if(screen==="book")renderBook();else if(screen==="tank")renderTank();else if(screen==="missions")renderMissions();else if(screen==="practice")renderPractice();}
    root.querySelectorAll("[data-screen]").forEach(b=>b.onclick=()=>{screen=b.dataset.screen;session=null;closeModal();renderScreen();});

    function keydown(e){if(screen!=="fishing"||!session)return;if(e.code==="Space"){e.preventDefault();if(["cast","bite"].includes(session.phase))pressMain(session,state);else setReeling(session,true);}if((e.key==="a"||e.key==="ArrowLeft")&&session.jump)yank(session,"left");if((e.key==="d"||e.key==="ArrowRight")&&session.jump)yank(session,"right");if((e.key==="w"||e.key==="ArrowUp")&&session.power>=99)usePower(session);if((e.key==="f"||e.key==="F")&&session.fever>=99)useFever(session);}
    function keyup(e){if(screen==="fishing"&&session&&e.code==="Space")setReeling(session,false);}
    window.addEventListener("keydown",keydown);window.addEventListener("keyup",keyup);

    function loop(now){if(destroyed)return;const dt=Math.min(.04,(now-last)/1000);last=now;refillEnergy(state);if(screen==="fishing"&&session){updateFishing(session,state,dt);renderFishing(ctx,session,W,H);updateFishingControls();}saveTimer+=dt;uiTimer+=dt;if(uiTimer>.35){uiTimer=0;top();if(screen==="tank")renderTank();}if(saveTimer>10){saveTimer=0;saveState(state);}raf=requestAnimationFrame(loop);}
    renderScreen();last=performance.now();raf=requestAnimationFrame(loop);
    return {destroy:()=>{destroyed=true;cancelAnimationFrame(raf);ro?.disconnect();window.removeEventListener("keydown",keydown);window.removeEventListener("keyup",keyup);saveState(state);style.remove();}};
  }
};
