import {REGIONS,FISH,RARITY} from './ReelEmpireData.js';
import {fmt,clamp} from './ReelEmpireEngine.js';
function rr(ctx,x,y,w,h,r){ctx.beginPath();ctx.roundRect(x,y,w,h,r);}
export function render(ctx,s,W,H){ctx.clearRect(0,0,W,H);const region=REGIONS.find(r=>r.id===s.region)||REGIONS[0];drawScene(ctx,s,region,W,H);drawBoat(ctx,W,H);drawLine(ctx,s,W,H);if(s.phase==='fighting'&&s.fish)drawFish(ctx,s,W,H);drawParticles(ctx,s,W,H);drawFloats(ctx,s,W,H);drawHud(ctx,s,W,H);}
function drawScene(ctx,s,r,W,H){const sky=ctx.createLinearGradient(0,0,0,H*.52);sky.addColorStop(0,r.sky);sky.addColorStop(1,'#d5d1ad');ctx.fillStyle=sky;ctx.fillRect(0,0,W,H*.52);ctx.fillStyle='rgba(255,239,165,.55)';ctx.beginPath();ctx.arc(W*.78,H*.14,30,0,Math.PI*2);ctx.fill();ctx.fillStyle='rgba(37,66,64,.35)';ctx.beginPath();ctx.moveTo(0,H*.43);for(let x=0;x<=W;x+=50)ctx.lineTo(x,H*.36+Math.sin(x*.015)*22+Math.sin(x*.037)*9);ctx.lineTo(W,H*.52);ctx.lineTo(0,H*.52);ctx.fill();const water=ctx.createLinearGradient(0,H*.47,0,H);water.addColorStop(0,r.water);water.addColorStop(1,'#102d43');ctx.fillStyle=water;ctx.fillRect(0,H*.47,W,H*.53);ctx.strokeStyle='rgba(207,248,255,.18)';ctx.lineWidth=1;for(let y=H*.52;y<H;y+=26){ctx.beginPath();for(let x=0;x<=W;x+=22){const yy=y+Math.sin(x*.028+s.totalCatches*.03+y*.01)*4;x?ctx.lineTo(x,yy):ctx.moveTo(x,yy);}ctx.stroke();}ctx.globalAlpha=.16;ctx.fillStyle='#071f2d';for(let i=0;i<13;i++){const x=(i*137+53)%W;ctx.beginPath();ctx.ellipse(x,H*.82+(i%3)*26,32+(i%4)*8,8,0,0,Math.PI*2);ctx.fill();}ctx.globalAlpha=1;}
function drawBoat(ctx,W,H){const x=W*.26,y=H*.45;ctx.save();ctx.translate(x,y);ctx.fillStyle='#9a633a';ctx.beginPath();ctx.moveTo(-72,0);ctx.lineTo(76,0);ctx.lineTo(47,28);ctx.lineTo(-48,28);ctx.closePath();ctx.fill();ctx.fillStyle='#d5b17b';ctx.fillRect(-45,-18,78,18);ctx.fillStyle='#20384a';ctx.fillRect(-8,-39,30,21);ctx.fillStyle='#e8ddbd';ctx.fillRect(-3,-35,20,11);ctx.strokeStyle='#2a2320';ctx.lineWidth=4;ctx.beginPath();ctx.moveTo(42,-12);ctx.quadraticCurveTo(105,-58,143,-5);ctx.stroke();ctx.fillStyle='#f1cc62';ctx.beginPath();ctx.arc(38,-13,8,0,Math.PI*2);ctx.fill();ctx.restore();}
function drawLine(ctx,s,W,H){const sx=W*.26+143,sy=H*.45-5,tx=s.phase==='fighting'?W*.63:W*.58,ty=s.phase==='fighting'?H*.67:H*.57;ctx.strokeStyle='rgba(240,244,245,.65)';ctx.lineWidth=1.5;ctx.beginPath();ctx.moveTo(sx,sy);ctx.quadraticCurveTo(W*.50,H*.50,tx,ty);ctx.stroke();ctx.fillStyle='#ebd45c';ctx.beginPath();ctx.arc(tx,ty,4,0,Math.PI*2);ctx.fill();}
function drawFish(ctx,s,W,H){const f=FISH[s.fish.id],x=W*.63+Math.sin(performance.now()/180)*9,y=H*.68+Math.sin(performance.now()/240)*6,rarity=RARITY[f.rarity],scale=clamp(1+s.fish.weight/(f.weight[1]*5),1,1.45)*(s.fish.trophy?1.22:1);ctx.save();ctx.translate(x,y);ctx.scale(scale,scale);ctx.shadowColor=rarity.color;ctx.shadowBlur=s.fish.trophy?20:8;ctx.fillStyle=f.color;ctx.beginPath();ctx.ellipse(0,0,44,20,0,0,Math.PI*2);ctx.fill();ctx.beginPath();ctx.moveTo(-40,0);ctx.lineTo(-68,-22);ctx.lineTo(-63,22);ctx.closePath();ctx.fill();ctx.fillStyle='rgba(255,255,255,.55)';ctx.beginPath();ctx.ellipse(11,-7,17,5,-.2,0,Math.PI*2);ctx.fill();ctx.fillStyle='#fff';ctx.beginPath();ctx.arc(27,-6,4,0,Math.PI*2);ctx.fill();ctx.fillStyle='#17222b';ctx.beginPath();ctx.arc(28,-6,2,0,Math.PI*2);ctx.fill();if(s.fish.trophy){ctx.strokeStyle='#f6d765';ctx.lineWidth=3;ctx.beginPath();ctx.arc(0,0,50,0,Math.PI*2);ctx.stroke();}ctx.restore();}
function drawParticles(ctx,s,W,H){for(const p of s.particles){const a=clamp(p.life/p.max,0,1),x=p.x*W,y=p.y*H,sz=9*(p.size||1);ctx.save();ctx.globalAlpha=Math.min(1,a*1.5);ctx.shadowColor=p.color;ctx.shadowBlur=6;ctx.fillStyle=p.color;if(p.kind==='coin'){ctx.beginPath();ctx.ellipse(x,y,sz*.7,sz,0,0,Math.PI*2);ctx.fill();}else if(p.kind==='star'||p.kind==='crit'){ctx.beginPath();for(let i=0;i<8;i++){const rr=i%2?sz*.35:sz,an=-Math.PI/2+i*Math.PI/4,xx=x+Math.cos(an)*rr,yy=y+Math.sin(an)*rr;i?ctx.lineTo(xx,yy):ctx.moveTo(xx,yy);}ctx.closePath();ctx.fill();}else{ctx.beginPath();ctx.arc(x,y,sz*.45,0,Math.PI*2);ctx.fill();}ctx.restore();}}
function drawFloats(ctx,s,W,H){for(const f of s.floats){const a=clamp(f.life/f.max,0,1);ctx.save();ctx.globalAlpha=Math.min(1,a*1.7);ctx.textAlign='center';ctx.font=`1000 ${Math.round(17*f.scale)}px sans-serif`;ctx.lineWidth=4;ctx.strokeStyle='#000a';ctx.strokeText(f.text,f.x*W,f.y*H);ctx.fillStyle=f.color;ctx.shadowColor=f.color;ctx.shadowBlur=8;ctx.fillText(f.text,f.x*W,f.y*H);ctx.restore();}}
function drawHud(ctx,s,W,H){ctx.textAlign='center';if(s.phase==='waiting'){ctx.fillStyle='rgba(5,15,21,.58)';rr(ctx,W*.37,H*.18,W*.26,48,11);ctx.fill();ctx.fillStyle='#e7f4f7';ctx.font='900 18px sans-serif';ctx.fillText('WAITING FOR A BITE',W*.5,H*.18+29);}else if(s.phase==='fighting'&&s.fish){const pct=clamp(s.fishStamina/s.maxStamina,0,1),bw=clamp(W*.43,280,520),x=W*.5-bw/2,y=H*.15;ctx.fillStyle='rgba(2,10,16,.72)';rr(ctx,x-4,y-4,bw+8,29,7);ctx.fill();ctx.fillStyle='#253843';rr(ctx,x,y,bw,21,5);ctx.fill();const g=ctx.createLinearGradient(x,0,x+bw,0);g.addColorStop(0,'#66d6c5');g.addColorStop(1,'#64a9e6');ctx.fillStyle=g;rr(ctx,x,y,bw*pct,21,5);ctx.fill();ctx.fillStyle='#fff';ctx.font='900 12px sans-serif';ctx.fillText(`${s.fish.name} · ${fmt(s.fishStamina)} / ${fmt(s.maxStamina)} stamina`,W*.5,y+15);ctx.fillStyle=RARITY[s.fish.rarity].color;ctx.font='800 11px sans-serif';ctx.fillText(`${s.fish.rarity.toUpperCase()} · ${s.fish.weight.toFixed(2)} kg${s.schoolCount>1?` · SCHOOL ×${s.schoolCount}`:''}`,W*.5,y+43);}else{ctx.fillStyle='#ffe17a';ctx.font='1000 18px sans-serif';ctx.fillText('CATCH LANDED!',W*.5,H*.21);}}
