import {REGIONS,FISH,RARITY,UPGRADES,RESEARCH,PRESTIGE} from './ReelEmpireData.js';
export const SAVE_KEY='reel-empire-idle-v1';
export const clamp=(v,a,b)=>Math.max(a,Math.min(b,v));
export const rand=(a,b)=>a+Math.random()*(b-a);
export function fmt(n){if(!Number.isFinite(n))return '∞';const a=Math.abs(n);if(a<1000)return a<10?n.toFixed(2).replace(/0+$/,'').replace(/\.$/,''):Math.floor(n).toString();const u=['K','M','B','T','Qa','Qi','Sx','Sp','Oc','No','Dc'];let x=a,i=-1;while(x>=1000&&i<u.length-1){x/=1000;i++;}return(n<0?'-':'')+x.toFixed(x>=100?0:x>=10?1:2).replace(/\.0+$|(\.\d*[1-9])0+$/,'$1')+u[i];}
export const xpNeed=l=>Math.floor(70*Math.pow(1.145,Math.max(0,l-1))+l*22);
function fresh(){return{version:1,coins:30,pearls:0,level:1,xp:0,totalXp:0,researchPoints:0,region:'pond',highestRegion:0,totalCatches:0,totalCoins:0,totalWeight:0,biggest:{},collection:{},upgrades:Object.fromEntries(UPGRADES.map(u=>[u.id,0])),research:{},prestige:{},prestigeCount:0,lastSave:Date.now(),phase:'waiting',phaseTimer:1.6,fish:null,fishStamina:0,maxStamina:0,tension:0,combo:0,comboTimer:0,lastCatch:null,schoolCount:1,particles:[],floats:[],stats:{crit:0,trophies:0,schools:0,mythics:0}};}
export function loadState(){const f=fresh();try{const raw=localStorage.getItem(SAVE_KEY);if(!raw)return f;const p=JSON.parse(raw);return{...f,...p,upgrades:{...f.upgrades,...(p.upgrades||{})},research:{...(p.research||{})},prestige:{...(p.prestige||{})},biggest:{...(p.biggest||{})},collection:{...(p.collection||{})},stats:{...f.stats,...(p.stats||{})},particles:[],floats:[],fish:null,phase:'waiting',phaseTimer:.8};}catch{return f;}}
export function saveState(s){s.lastSave=Date.now();try{localStorage.setItem(SAVE_KEY,JSON.stringify({...s,particles:[],floats:[],fish:null}));}catch{}}
export const upgradeCost=(u,lv)=>Math.floor(u.baseCost*Math.pow(u.scale,lv));
export function upgradeValue(u,lv){let v=u.base+u.growth*lv;if(u.min!=null)v=Math.max(u.min,v);if(u.max!=null)v=Math.min(u.max,v);return v;}
export function previewUpgrade(s,id){const u=UPGRADES.find(x=>x.id===id);if(!u)return null;const lv=s.upgrades[id]||0,cur=upgradeValue(u,lv),next=upgradeValue(u,lv+1),cost=upgradeCost(u,lv),scale=u.displayScale||1;const f=v=>{const vv=v*scale;if(u.unit==='s')return vv.toFixed(2)+'s';if(u.unit==='%')return vv.toFixed(1)+'%';if(u.unit==='×')return vv.toFixed(2)+'×';if(u.unit==='/s')return vv.toFixed(1)+'/s';return vv>=100?Math.round(vv).toString():vv.toFixed(vv<10?2:1).replace(/\.0$/,'');};return{u,lv,cur,next,cost,currentText:f(cur),nextText:f(next)};}
export function buyUpgrade(s,id){const p=previewUpgrade(s,id);if(!p||s.level<p.u.unlock||s.coins<p.cost)return false;s.coins-=p.cost;s.upgrades[id]=p.lv+1;return true;}
function researchValue(s,e){let v=0;for(const r of RESEARCH)if(r.effect===e)v+=r.value*(s.research[r.id]||0);return v;}
function prestigeValue(s,e){const p=PRESTIGE.find(x=>x.effect===e);return p?p.value*(s.prestige[p.id]||0):0;}
export function mods(s){const U=id=>UPGRADES.find(x=>x.id===id),V=id=>upgradeValue(U(id),s.upgrades[id]||0),all=1+researchValue(s,'all');return{hook:V('hook')*all*(1+prestigeValue(s,'power')),auto:(V('reel')+V('crew'))*(1+researchValue(s,'passive'))*all*(1+prestigeValue(s,'power')),bite:V('bait'),line:V('line'),sale:V('net')*V('market')*(1+researchValue(s,'gold'))*all*(1+prestigeValue(s,'gold')),rare:V('sonar')+prestigeValue(s,'rare'),offline:clamp(V('cooler')+researchValue(s,'offline'),0,1),weight:V('radar'),cast:V('autocast'),double:V('luck'),boss:V('engine')*(1+researchValue(s,'boss')),xp:V('hatchery')*all*(1+prestigeValue(s,'xp')),crit:researchValue(s,'crit'),combo:researchValue(s,'combo'),school:researchValue(s,'school'),trophy:researchValue(s,'trophy')+prestigeValue(s,'rare')*.35};}
export function canTravel(s,id){const r=REGIONS.find(x=>x.id===id);return!!r&&s.level>=r.unlockLevel;}
export function travel(s,id){if(!canTravel(s,id))return false;s.region=id;s.phase='waiting';s.phaseTimer=.5;s.fish=null;return true;}
function availableRegionIndex(s){let idx=0;for(let i=0;i<REGIONS.length;i++)if(s.level>=REGIONS[i].unlockLevel)idx=i;return idx;}
function chooseFish(s){const region=REGIONS.find(r=>r.id===s.region)||REGIONS[0],m=mods(s),choices=region.fish.map(id=>{const f=FISH[id],ri=['Common','Uncommon','Rare','Epic','Legendary','Mythic'].indexOf(f.rarity);return[id,RARITY[f.rarity].weight/Math.pow(1+m.rare*3.6,ri)];});let total=choices.reduce((a,b)=>a+b[1],0),roll=Math.random()*total;for(const[id,w]of choices){roll-=w;if(roll<=0)return id;}return choices[0][0];}
function addFloat(s,text,color='#fff',scale=1,x=.5,y=.42){s.floats.push({text,color,scale,life:1,max:1,x,y,vx:rand(-.02,.02),vy:-.18});}
function particles(s,kind,count,color){for(let i=0;i<count;i++)s.particles.push({kind,color,life:rand(.5,1.2),max:1.2,x:.5+rand(-.08,.08),y:.54+rand(-.05,.05),vx:rand(-.25,.25),vy:rand(-.45,-.12),g:.45,size:rand(.6,1.4)});}
function startWaiting(s){const m=mods(s);s.phase='waiting';s.phaseTimer=rand(m.bite*.72,m.bite*1.28);s.fish=null;s.tension=0;}
function hookFish(s){const id=chooseFish(s),f=FISH[id],region=REGIONS.find(r=>r.id===s.region),m=mods(s);let weight=rand(f.weight[0],f.weight[1])*m.weight;const trophy=Math.random()<clamp(.025+m.trophy,0,.35);if(trophy){weight*=rand(1.5,2.35);s.stats.trophies++;}const stamina=(18+f.power*17)*region.mult*Math.pow(1.055,s.level-1)*(trophy?1.7:1);s.fish={id,name:f.name,rarity:f.rarity,color:f.color,weight,trophy,region:region.id};s.maxStamina=stamina;s.fishStamina=stamina;s.tension=30;s.phase='fighting';s.combo=0;s.comboTimer=0;s.schoolCount=Math.random()<clamp(m.school,0,.40)?Math.floor(rand(2,5)):1;if(s.schoolCount>1)s.stats.schools++;addFloat(s,trophy?`TROPHY ${f.name.toUpperCase()}!`:`${f.name.toUpperCase()} BITES!`,RARITY[f.rarity].color,trophy?1.25:1,.5,.28);}
export function pulseReel(s){if(s.phase!=='fighting'||!s.fish)return{damage:0,crit:false};const m=mods(s);let dmg=m.hook,crit=Math.random()<clamp(m.crit,0,.65);if(crit){dmg*=2;s.stats.crit++;}s.combo=Math.min(100,s.combo+1);s.comboTimer=.62;dmg*=1+s.combo*(.0025+m.combo*.006);if(s.fish.trophy||s.fish.rarity==='Mythic')dmg*=m.boss;s.fishStamina=Math.max(0,s.fishStamina-dmg);s.tension=clamp(s.tension+rand(4,9),0,m.line);addFloat(s,fmt(dmg),crit?'#74ff9b':'#f6fbff',crit?1.22:.95,rand(.43,.57),rand(.39,.49));particles(s,crit?'crit':'splash',crit?6:3,crit?'#74ff9b':'#8cecff');if(s.fishStamina<=0)landFish(s);return{damage:dmg,crit};}
function landFish(s){const f=s.fish,region=REGIONS.find(r=>r.id===f.region),def=FISH[f.id],m=mods(s);let count=s.schoolCount||1,base=f.weight*def.value*region.mult*5.5*m.sale,xp=(8+f.weight*def.power*1.4)*region.mult*m.xp;if(f.trophy){base*=2.8;xp*=2;}if(Math.random()<clamp(m.double,0,.55)){count*=2;addFloat(s,'DOUBLE CATCH!','#ffe26b',1.15,.5,.33);}base*=count;xp*=count;s.coins+=base;s.totalCoins+=base;s.xp+=xp;s.totalXp+=xp;s.totalCatches+=count;s.totalWeight+=f.weight*count;s.collection[f.id]=(s.collection[f.id]||0)+count;s.biggest[f.id]=Math.max(s.biggest[f.id]||0,f.weight);s.lastCatch={...f,count,value:base,xp};if(f.rarity==='Mythic')s.stats.mythics++;addFloat(s,`+${fmt(base)} COINS`,'#ffd85c',1.08,.5,.31);particles(s,'coin',Math.min(32,10+count*4),'#ffd85c');while(s.xp>=xpNeed(s.level)){s.xp-=xpNeed(s.level);s.level++;s.researchPoints++;addFloat(s,`LEVEL ${s.level}!`,'#7cecff',1.3,.5,.23);particles(s,'star',12,'#7cecff');}s.highestRegion=Math.max(s.highestRegion,availableRegionIndex(s));s.phase='landing';s.phaseTimer=m.cast;}
export function update(s,dt){if(s.phase==='waiting'){s.phaseTimer-=dt;if(s.phaseTimer<=0)hookFish(s);}else if(s.phase==='fighting'){const m=mods(s),boss=(s.fish?.trophy||s.fish?.rarity==='Mythic')?m.boss:1;s.fishStamina=Math.max(0,s.fishStamina-m.auto*boss*dt);s.tension=Math.max(12,s.tension-18*dt);if(s.fishStamina<=0)landFish(s);}else if(s.phase==='landing'){s.phaseTimer-=dt;if(s.phaseTimer<=0)startWaiting(s);}if(s.comboTimer>0){s.comboTimer-=dt;if(s.comboTimer<=0)s.combo=0;}for(const p of s.particles){p.life-=dt;p.x+=p.vx*dt;p.y+=p.vy*dt;p.vy+=p.g*dt;}s.particles=s.particles.filter(p=>p.life>0);for(const f of s.floats){f.life-=dt;f.x+=f.vx*dt;f.y+=f.vy*dt;}s.floats=s.floats.filter(f=>f.life>0);}
export function buyResearch(s,id){const r=RESEARCH.find(x=>x.id===id);if(!r)return false;const lv=s.research[id]||0;if(lv>=r.max)return false;const cost=r.cost*(1+Math.floor(lv/3));if(s.researchPoints<cost)return false;s.researchPoints-=cost;s.research[id]=lv+1;return true;}
export function prestigeGain(s){if(s.level<25)return 0;return Math.max(1,Math.floor((s.level-20)/6+Math.sqrt(Math.max(0,s.totalCatches))/35));}
export function buyPrestige(s,id){const p=PRESTIGE.find(x=>x.id===id);if(!p)return false;const lv=s.prestige[id]||0,cost=Math.ceil(p.baseCost*Math.pow(p.scale,lv));if(s.pearls<cost)return false;s.pearls-=cost;s.prestige[id]=lv+1;return true;}
export function voyagePrestige(s){const gain=prestigeGain(s);if(gain<=0)return false;s.pearls+=gain;s.prestigeCount++;const keep={pearls:s.pearls,prestige:{...s.prestige},biggest:{...s.biggest},collection:{...s.collection},stats:{...s.stats},prestigeCount:s.prestigeCount,totalCatches:s.totalCatches,totalCoins:s.totalCoins,totalWeight:s.totalWeight,totalXp:s.totalXp};Object.assign(s,fresh(),keep);const start=prestigeValue(s,'start');s.level=1+Math.floor(start)*5;s.highestRegion=availableRegionIndex(s);s.region=REGIONS[s.highestRegion].id;startWaiting(s);return gain;}
export function applyOffline(s,now=Date.now()){const sec=clamp((now-(s.lastSave||now))/1000,0,8*3600);if(sec<10)return{seconds:0,catches:0,coins:0};const m=mods(s),region=REGIONS.find(r=>r.id===s.region)||REGIONS[0],avgPower=m.auto+m.hook*.45,avgStam=(18+2.4*17)*region.mult*Math.pow(1.055,s.level-1),cycle=m.bite+m.cast+avgStam/Math.max(.1,avgPower),catches=Math.floor(sec*m.offline/Math.max(.8,cycle)),coins=catches*region.mult*18*m.sale;s.coins+=coins;s.totalCoins+=coins;s.totalCatches+=catches;const xp=catches*region.mult*12*m.xp;s.xp+=xp;s.totalXp+=xp;while(s.xp>=xpNeed(s.level)){s.xp-=xpNeed(s.level);s.level++;s.researchPoints++;}s.lastSave=now;return{seconds:sec,catches,coins};}
